import z from "@deepseek-ai/schemastery";
import { dump } from "js-yaml";
import { installSettingsSection, settingsNamespace } from "@deepseek-ai/dsh-settings";
import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
//#region src/preset-install.ts
/**
* Publishes the council as an agent PRESET — the entry the Web composer's mode
* menu lists beside Standard, PTC, Minimal and Creator.
*
* A preset is a directory under a roster root holding `agent.cordis.yml` (the
* agent-plane composition) and `preset.yml` (its display metadata). The roster
* always scans `$DSH_HOME/.agent-presets` — that is `dsh-agent-presets`' own
* `includeUserRoot` default — so writing a directory there is the whole
* installation. Discovery is unmemoized, so the mode appears without a restart.
*
* Deriving rather than vendoring. The composition is a WHOLE agent plane, not a
* delta: `standard` is ~250 rows. Shipping a snapshot of it would silently drift
* from the harness on every upgrade and compose a mode out of last release's
* rows. So the source text is read back from the installed roster through
* `read()` and this package appends only its own rows — the mode is always the
* current harness plus the council.
*
* Why the roster is read structurally. `@deepseek-ai/dsh-agent-presets` is
* supplied by the harness installation, not by this package, and the npm-published
* copy lags the installed one. Naming the shape here rather than importing it
* keeps the plugin loadable against either, and the two members used are the ones
* the service README documents.
*
* @module @starsinc1708/dsh-tool-council
*/
/** Preset ids the roster accepts as directory names. */
const PRESET_ID = /^[a-z0-9][a-z0-9-]*$/u;
/** Marker line carrying the derivation stamp, so a rewrite is decidable. */
const STAMP_PREFIX = "# dsh-tool-council:stamp ";
/**
* Compose the preset's `agent.cordis.yml` from its source composition.
*
* The stamp covers the source text AND the appended rows, so an upgraded
* harness (new source) and a reconfigured council (new rows) both invalidate an
* installed copy, while a byte-identical derivation rewrites nothing.
* @param source - the source preset's composition text, verbatim.
* @param rows - this package's rows, as YAML list entries.
* @param sourceId - the source preset's id, recorded in the header.
* @returns the composition text to write, stamp included.
*/
function composePreset(source, rows, sourceId) {
	const stamp = createHash("sha256").update(source).update("\0").update(rows).digest("hex").slice(0, 16);
	const body = `${source.trimEnd()}\n\n${rows.trimEnd()}\n`;
	return [
		`# GENERATED by @starsinc1708/dsh-tool-council — derived from the "${sourceId}" preset.`,
		"#",
		"# Edits are lost: the plugin rewrites this file whenever the source preset or",
		"# its own rows change. To diverge, copy this directory under a new id and",
		"# remove that preset from the plugin config (installPreset: false).",
		`${STAMP_PREFIX}${stamp}`,
		"",
		body
	].join("\n");
}
/**
* Read the stamp a previously installed composition carries.
* @param text - an installed `agent.cordis.yml`.
* @returns the stamp, or undefined when the file is absent or hand-written.
*/
function readStamp(text) {
	for (const line of text.split("\n", 16)) if (line.startsWith(STAMP_PREFIX)) return line.slice(25).trim();
}
/**
* Render `preset.yml`. The roster localizes only `system`-trust built-ins, so a
* user-trust preset's own metadata is what the mode menu shows, verbatim.
* @param options - the display metadata.
* @returns the file text.
*/
function composeMetadata(options) {
	return [
		`name: ${JSON.stringify(options.name)}`,
		`description: ${JSON.stringify(options.description)}`,
		`order: ${options.order}`,
		""
	].join("\n");
}
/**
* Publish the council preset into the roster's writable root, idempotently.
*
* Never throws for a deployment that cannot carry a preset — the tool itself
* stays usable in whatever mode the deployment does compose.
* @param presets - the roster service, or undefined when none is composed.
* @param options - what to publish.
* @returns what happened, for the caller to log.
*/
async function ensurePreset(presets, options) {
	if (presets === void 0) return {
		kind: "skipped",
		reason: "no agent-preset roster is composed"
	};
	if (!PRESET_ID.test(options.presetId)) return {
		kind: "failed",
		reason: `preset id ${JSON.stringify(options.presetId)} is not a usable directory name`
	};
	const root = presets.roots.find((candidate) => candidate.trust === "user");
	if (root === void 0) return {
		kind: "skipped",
		reason: "the roster exposes no writable root"
	};
	let source;
	try {
		source = await presets.read(options.sourceId);
	} catch (error) {
		return {
			kind: "skipped",
			reason: `source preset ${JSON.stringify(options.sourceId)} is unreadable — ${messageOf(error)}`
		};
	}
	const composition = composePreset(source, options.rows, options.sourceId);
	const directory = join(root.path, options.presetId);
	const compositionPath = join(directory, "agent.cordis.yml");
	const installed = await readIfPresent(compositionPath);
	if (installed !== void 0 && readStamp(installed) === readStamp(composition)) return {
		kind: "unchanged",
		path: directory
	};
	try {
		await mkdir(directory, { recursive: true });
		await writeFile(compositionPath, composition, "utf8");
		await writeFile(join(directory, "preset.yml"), composeMetadata(options), "utf8");
	} catch (error) {
		return {
			kind: "failed",
			reason: `could not write ${directory} — ${messageOf(error)}`
		};
	}
	return {
		kind: "installed",
		path: directory
	};
}
/**
* Read a file, treating absence as absence rather than as an error.
* @param path - the file to read.
* @returns its text, or undefined when it does not exist.
*/
async function readIfPresent(path) {
	try {
		return await readFile(path, "utf8");
	} catch {
		return;
	}
}
/**
* One line describing a thrown value.
* @param error - the thrown value.
* @returns its message, or its string form.
*/
function messageOf(error) {
	return error instanceof Error ? error.message : String(error);
}
//#endregion
//#region src/settings.ts
/** The settings namespace this package serves. */
const COUNCIL_NAMESPACE = "council";
/**
* Project the composition's presets into the browser-facing mirror.
* @param presets - the deployment's resolved presets.
* @returns the same topology with prompts and framing dropped.
*/
function toTopology(presets) {
	return presets.map((preset) => ({
		id: preset.id,
		label: preset.label ?? preset.id,
		description: preset.description,
		layers: preset.layers.map((layer) => ({
			id: layer.id,
			kind: layer.kind,
			roles: layer.roles.map((role) => ({
				id: role.id,
				label: role.label ?? role.id,
				count: role.count ?? 1,
				model: role.model ?? "",
				provider: role.provider ?? ""
			})),
			...layer.quorum === void 0 ? {} : {
				quorumRule: layer.quorum.rule,
				...layer.quorum.threshold === void 0 ? {} : { quorumThreshold: layer.quorum.threshold }
			}
		}))
	}));
}
//#endregion
//#region src/presets.ts
/**
* Shared contract every map child obeys. Kept in one place because a finding
* that omits `location` cannot be deduplicated and a finding that restates its
* own claim as `evidence` cannot be verified — both failures are silent.
*/
const MAP_CONTRACT = [
	"Report only what you verified yourself in the workspace. Open the files, run what you can.",
	"Every finding needs a concrete `location` as `path:line` (or `path` when the whole file is the subject) — it is the deduplication key, and a finding without one is discarded.",
	"`evidence` must be an observation: a quoted line, a reproduction, a failing assertion. Restating `claim` in other words is not evidence and will be voted down.",
	"Report nothing rather than something plausible. A speculative finding costs three verifiers their time and trains the reader to distrust the table.",
	"Stay inside your lens. Another role covers the ground you are tempted to stray into."
].join("\n");
/**
* Shared contract every verifier obeys. The independence clause is the point
* of the layer: a verifier that reasons from the finding text alone measures
* how convincing the wording is, not whether the claim holds.
*/
const VERIFY_CONTRACT = [
	"For each finding, go back to the cited location and form your own judgement from the source. Do not reason from the finding text alone.",
	"Vote `confirmed` only when you reproduced the problem or read the defect yourself.",
	"Vote `rejected` when the factual claim is wrong.",
	"Vote `not-a-bug` when the claim is factually right but the behaviour is correct, intended, or already handled elsewhere — say where.",
	"Vote `uncertain` when you could not reach the evidence. It is an honest answer and it never counts toward confirmation, so use it instead of guessing.",
	"`reason` is mandatory and must name what you looked at. \"Looks right\" is not a reason.",
	"You are graded on being right, not on agreeing. A well-argued rejection is the most valuable thing you can produce."
].join("\n");
/** The four shipped topologies. */
const BUILTIN_PRESETS = [
	{
		id: "bug-hunt",
		label: "Bug hunt",
		description: "Find defects in a diff, module, or design, then cross-verify each one independently. Use when the answer is a list of discrete problems.",
		reduceMode: "vote",
		framing: "A council of independent agents is auditing the subject below. You are one member. You share the workspace but no conversation.",
		layers: [
			{
				id: "map",
				kind: "map",
				roles: [
					{
						id: "correctness",
						label: "Correctness",
						prompt: `Your lens is logic and data flow. Look for inverted comparisons, wrong operands, off-by-one, sign errors, mixed-up units or estimators, unhandled empty and null cases, and state that is read before it is written.\n\n${MAP_CONTRACT}`
					},
					{
						id: "api-contract",
						label: "API contract",
						prompt: `Your lens is the seams between modules. Look for callers passing arguments the callee no longer accepts, renamed or reordered parameters, return shapes that changed, duplicated logic whose copies have already diverged, and invariants documented in one place and enforced in another.\n\n${MAP_CONTRACT}`
					},
					{
						id: "perf-scale",
						label: "Performance & scale",
						prompt: `Your lens is what happens at production size. Look for accidental quadratic work, per-row allocations in hot loops, unbounded collections, exact algorithms where an approximate one is assumed (and the reverse), and work repeated per call that could be hoisted.\n\n${MAP_CONTRACT}`
					},
					{
						id: "tests",
						label: "Tests",
						prompt: `Your lens is the test suite. Look for tests that will fail on this change, tests that assert the old behaviour, tolerances too tight or too loose for the arithmetic involved, and behaviour with no test at all. When a test must change, say whether the fix is the expectation or the tolerance — they are different bugs.\n\n${MAP_CONTRACT}`
					}
				]
			},
			{
				id: "verify",
				kind: "verify",
				quorum: { rule: "majority" },
				roles: [
					{
						id: "V1",
						label: "Replicator",
						prompt: `You re-derive. Go to each cited location and work out from the source whether the claim holds, as if you had never seen the finding. Ignore how confident the author sounded.\n\n${VERIFY_CONTRACT}`
					},
					{
						id: "V2",
						label: "Devil's advocate",
						prompt: `You argue the other side. For each finding, build the strongest case that it is NOT a defect: the behaviour is intended, the caller already guarantees the precondition, the path is unreachable, the author misread the code. Then vote honestly on whether your own case survived contact with the source. A finding you could not argue away is strong evidence, and saying so is the right answer.\n\n${VERIFY_CONTRACT}`
					},
					{
						id: "V3",
						label: "Impact",
						prompt: `You assume the claim is true and ask what it costs. Trace who reaches this code, under what inputs, and what a user sees when it goes wrong. A true statement about dead code, a debug-only path, or an already-guarded case is real but is \`not-a-bug\` for action purposes — vote that way and say why.\n\n${VERIFY_CONTRACT}`
					}
				]
			},
			{
				id: "reduce",
				kind: "reduce",
				roles: [{
					id: "synthesizer",
					label: "Synthesizer",
					prompt: [
						"You write the final report from the verdict table you are given. You do not re-litigate votes and you do not add findings of your own.",
						"",
						"Produce, in this order:",
						"1. One paragraph: what was audited and what the council concluded.",
						"2. The confirmed findings, ordered by what a maintainer should fix first — severity and blast radius, not the order they arrived in. For each: the defect in one line, the location, and the concrete change.",
						"3. Rejected and not-a-bug findings in one compact list with the one-line reason each was set aside. This section is why the reader can trust the first one; never drop it.",
						"4. Anything marked uncertain or insufficient, named as unresolved rather than silently omitted.",
						"",
						"Attribute conclusions to the council, not to certainty: \"two of three verifiers confirmed\", not \"confirmed\". Verifiers are agents re-reading the same repository, not an independent oracle."
					].join("\n")
				}]
			}
		]
	},
	{
		id: "research",
		label: "Research",
		description: "Investigate a question from several angles at once and merge the results into one document. Use when the answer is prose, not a defect list.",
		reduceMode: "synthesis",
		framing: "A council of independent researchers is investigating the question below. You are one member. Work only from sources you can actually reach.",
		layers: [{
			id: "map",
			kind: "map",
			roles: [
				{
					id: "prior-art",
					label: "Prior art",
					prompt: "Find what already exists — in this repository, in its dependencies, and in the documented state of the art. Report what each option actually does, with references. Say plainly when you found nothing."
				},
				{
					id: "constraints",
					label: "Constraints",
					prompt: "Establish the hard limits: what the current architecture, data volumes, dependencies, platform floors, and stated invariants make impossible or expensive. Cite where each constraint is written down or measured."
				},
				{
					id: "tradeoffs",
					label: "Trade-offs",
					prompt: "For the candidate directions, lay out what each one costs and what it buys — complexity, runtime, migration, ongoing maintenance. Refuse to declare a winner; that is the reducer's job and premature ranking hides the alternatives."
				},
				{
					id: "risks",
					label: "Risks & unknowns",
					prompt: "Name what could go wrong and what nobody has established yet. Distinguish \"we measured this and it is bad\" from \"nobody has measured this\". Unknowns are findings."
				}
			]
		}, {
			id: "reduce",
			kind: "reduce",
			roles: [{
				id: "synthesizer",
				label: "Synthesizer",
				prompt: "Merge the members' reports into one document: the question, what is established (with sources), where the members disagreed and on what evidence, what remains unknown, and what you would do next. Preserve disagreement instead of averaging it — two members contradicting each other is a result, not noise."
			}]
		}]
	},
	{
		id: "feature-design",
		label: "Feature design",
		description: "Explore competing designs for a feature, have them criticised, and pick one with the trade-offs written down. Use for ADRs and design reviews.",
		reduceMode: "synthesis",
		framing: "A design council is choosing an approach for the work below. You are one member. Ground every claim in this repository as it exists today.",
		layers: [
			{
				id: "map",
				kind: "map",
				roles: [
					{
						id: "minimal",
						label: "Minimal",
						prompt: "Design the smallest change that genuinely solves the problem. Reuse what exists. Name explicitly what you are choosing not to support and why that is acceptable."
					},
					{
						id: "idiomatic",
						label: "Idiomatic",
						prompt: "Design the version that fits this codebase's existing conventions and extension points best, even if it is larger. Cite the patterns you are following and where they are established."
					},
					{
						id: "ambitious",
						label: "Ambitious",
						prompt: "Design the version that would still be right in two years, then state honestly what it costs now and which parts could be deferred without painting the project into a corner."
					}
				]
			},
			{
				id: "verify",
				kind: "verify",
				quorum: { rule: "majority" },
				roles: [{
					id: "V1",
					label: "Feasibility",
					prompt: `Treat each proposal as a claim that it can be built here. Check its assumptions against the actual code: do the APIs it needs exist with those signatures, are the extension points real, does the build allow it? Vote \`rejected\` on a proposal resting on something that is not there.\n\n${VERIFY_CONTRACT}`
				}, {
					id: "V2",
					label: "Maintenance",
					prompt: `Judge each proposal by what it does to whoever maintains it. Look for duplicated invariants, config that must be kept in sync by hand, test surface that will rot, and abstractions with exactly one implementation. Vote \`not-a-bug\` when a cost is real but genuinely acceptable, and say why.\n\n${VERIFY_CONTRACT}`
				}]
			},
			{
				id: "reduce",
				kind: "reduce",
				roles: [{
					id: "synthesizer",
					label: "Synthesizer",
					prompt: "Write a decision record: the problem, the options as proposed, what the critics established about each, the recommendation, and the consequences the team accepts by taking it. If the critics killed every option, say that and describe what would have to change instead of picking the least damaged one."
				}]
			}
		]
	},
	{
		id: "refactor",
		label: "Refactor safety",
		description: "Plan a refactor and have the plan checked for regression risk before anything is changed. Use before touching code with weak test coverage.",
		reduceMode: "vote",
		framing: "A council is assessing the refactor described below. Nothing is being changed yet: the output is a plan and its risks.",
		layers: [
			{
				id: "map",
				kind: "map",
				roles: [{
					id: "plan",
					label: "Plan",
					prompt: `Produce the ordered sequence of mechanical steps, each independently reviewable and each leaving the tree building. Report each step as a finding whose \`location\` is the file it touches.\n\n${MAP_CONTRACT}`
				}, {
					id: "coupling",
					label: "Coupling",
					prompt: `Map what actually depends on the code being moved: callers, tests, generated artifacts, config that names symbols by string, and documentation asserting the current shape. Report each unnoticed dependency as a finding.\n\n${MAP_CONTRACT}`
				}]
			},
			{
				id: "verify",
				kind: "verify",
				quorum: { rule: "unanimous" },
				roles: [
					{
						id: "V1",
						label: "Behaviour",
						prompt: `For each step, decide whether it is genuinely behaviour-preserving. Look for silently changed evaluation order, defaults, error paths, and identity comparisons. Vote \`rejected\` on any step that changes observable behaviour while claiming not to.\n\n${VERIFY_CONTRACT}`
					},
					{
						id: "V2",
						label: "Coverage",
						prompt: `For each step, decide whether an existing test would actually catch a mistake in it. Untested surface is the finding, not the refactor itself. Vote \`uncertain\` when you cannot tell which test covers a path — that is exactly the signal the reader needs.\n\n${VERIFY_CONTRACT}`
					},
					{
						id: "V3",
						label: "Rollback",
						prompt: `For each step, decide whether it can be reverted alone once merged. Data migrations, on-disk format changes, and published contracts are one-way doors; flag them as such.\n\n${VERIFY_CONTRACT}`
					}
				]
			},
			{
				id: "reduce",
				kind: "reduce",
				roles: [{
					id: "synthesizer",
					label: "Synthesizer",
					prompt: "Write the refactor plan: the ordered steps that passed unanimously, then the steps that did not with the specific objection against each, then the one-way doors, then what to test first. A unanimous quorum means a single objection blocks a step — present blocked steps as work to be redesigned, not as work to be done carefully."
				}]
			}
		]
	}
];
//#endregion
//#region src/policy.ts
/**
* The council's deployment policy: the schema, the structural validation, and
* the role expansion. Owned here, apart from the tool and the host rows, so the
* always-composed host row can validate the same policy it publishes and mirrors
* without dragging in the tool's `ctx.tools`/workflow dependencies.
*
* @module @starsinc1708/dsh-tool-council
*/
const Quorum = z.object({
	rule: z.union([
		"majority",
		"unanimous",
		"threshold"
	]).default("majority"),
	threshold: z.number().step(1).min(1).max(Number.MAX_SAFE_INTEGER)
});
const Role = z.object({
	id: z.string().required(),
	label: z.string(),
	prompt: z.string().required(),
	count: z.number().step(1).min(1).max(Number.MAX_SAFE_INTEGER).default(1),
	model: z.string(),
	provider: z.string()
});
const Layer = z.object({
	id: z.string().required(),
	kind: z.union([
		"map",
		"verify",
		"reduce"
	]).required(),
	label: z.string(),
	roles: z.array(Role).default([]),
	quorum: Quorum.default(void 0)
});
const Preset = z.object({
	id: z.string().required(),
	label: z.string(),
	description: z.string().required(),
	reduceMode: z.union(["vote", "synthesis"]).default("vote"),
	framing: z.string().default(""),
	layers: z.array(Layer).default([])
});
z.object({
	toolName: z.string().default("council"),
	subagentProvider: z.string().default("spawn"),
	presets: z.array(Preset).default([...BUILTIN_PRESETS]),
	defaultPreset: z.string().default("bug-hunt"),
	maxAgentsPerLayer: z.number().step(1).min(1).max(100).default(100),
	maxLayers: z.number().step(1).min(1).max(16).default(6),
	maxFindings: z.number().step(1).min(1).max(1e4).default(200),
	maxFindingsPerMember: z.number().step(1).min(0).max(1e4).default(50),
	maxFindingChars: z.number().step(1).min(1).max(1e5).default(2e3),
	maxReportChars: z.number().step(1).min(1).max(1e6).default(32768),
	maxRunMs: z.number().step(1).min(0).max(864e5).default(0),
	retryFailedMembers: z.boolean().default(true),
	mergeSameLocation: z.boolean().default(true),
	maxMergeCandidates: z.number().step(1).min(2).max(1e3).default(60),
	councilEveryRequest: z.boolean().default(true)
});
/**
* Validate the composition at load, not at call.
*
* Schemastery cannot express the structural rules a council depends on — one
* trailing reduce layer with exactly one role, a quorum exactly where a verify
* layer is, unique ids — and a topology that violates them produces a run that
* silently drops a layer instead of failing. A bad config must break the
* deployment.
* @param config - the loader-normalized configuration.
* @returns the validated policy every call reuses.
* @throws TypeError on any structural violation, naming the offending preset.
*/
function resolveConfig(config) {
	const presets = config.presets ?? [...BUILTIN_PRESETS];
	const maxAgentsPerLayer = config.maxAgentsPerLayer ?? 100;
	const maxLayers = config.maxLayers ?? 6;
	if (presets.length === 0) throw new TypeError("council: at least one preset is required");
	const ids = /* @__PURE__ */ new Set();
	for (const preset of presets) {
		const where = `council preset "${preset.id}"`;
		if (ids.has(preset.id)) throw new TypeError(`${where}: duplicate preset id`);
		ids.add(preset.id);
		if (preset.layers.length === 0) throw new TypeError(`${where}: has no layers`);
		if (preset.layers.length > maxLayers) throw new TypeError(`${where}: ${preset.layers.length} layers exceeds maxLayers ${maxLayers}`);
		const last = preset.layers[preset.layers.length - 1];
		/* v8 ignore next -- length was checked above; the index cannot be empty. */
		if (last === void 0) throw new TypeError(`${where}: has no layers`);
		if (last.kind !== "reduce") throw new TypeError(`${where}: the last layer must be a reduce layer`);
		if (preset.layers.slice(0, -1).some((layer) => layer.kind === "reduce")) throw new TypeError(`${where}: only the last layer may be a reduce layer`);
		const verifyCount = preset.layers.filter((layer) => layer.kind === "verify").length;
		if (verifyCount > 1) throw new TypeError(`${where}: at most one verify layer is supported (${verifyCount} declared)`);
		const verifyAt = preset.layers.findIndex((layer) => layer.kind === "verify");
		if (verifyAt >= 0 && preset.layers.slice(verifyAt + 1).some((layer) => layer.kind === "map")) throw new TypeError(`${where}: a map layer may not follow the verify layer`);
		validateLayers(preset, maxAgentsPerLayer, where);
	}
	const defaultId = config.defaultPreset ?? "bug-hunt";
	const defaultPreset = presets.find((preset) => preset.id === defaultId);
	if (defaultPreset === void 0) throw new TypeError(`council: defaultPreset "${defaultId}" is not among the configured presets`);
	return {
		toolName: config.toolName ?? "council",
		subagentProvider: config.subagentProvider ?? "spawn",
		presets,
		defaultPreset,
		maxAgentsPerLayer,
		maxLayers,
		maxFindings: config.maxFindings ?? 200,
		maxFindingsPerMember: config.maxFindingsPerMember ?? 50,
		maxFindingChars: config.maxFindingChars ?? 2e3,
		maxReportChars: config.maxReportChars ?? 32768,
		maxRunMs: config.maxRunMs ?? 0,
		retryFailedMembers: config.retryFailedMembers ?? true,
		mergeSameLocation: config.mergeSameLocation ?? true,
		maxMergeCandidates: config.maxMergeCandidates ?? 60,
		councilEveryRequest: config.councilEveryRequest ?? true
	};
}
/**
* Validate every layer of one preset.
* @param preset - the preset under validation.
* @param maxAgentsPerLayer - the deployment's width ceiling.
* @param where - the error prefix naming the preset.
* @throws TypeError on a duplicate id, a misplaced quorum, or an over-wide layer.
*/
function validateLayers(preset, maxAgentsPerLayer, where) {
	const layerIds = /* @__PURE__ */ new Set();
	const roleIds = /* @__PURE__ */ new Set();
	for (const layer of preset.layers) {
		if (layerIds.has(layer.id)) throw new TypeError(`${where}: duplicate layer id "${layer.id}"`);
		layerIds.add(layer.id);
		if (layer.roles.length === 0) throw new TypeError(`${where}: layer "${layer.id}" has no roles`);
		const width = layer.roles.reduce((sum, role) => sum + (role.count ?? 1), 0);
		if (width > maxAgentsPerLayer) throw new TypeError(`${where}: layer "${layer.id}" width ${width} exceeds maxAgentsPerLayer ${maxAgentsPerLayer}`);
		for (const role of layer.roles) {
			if (roleIds.has(role.id)) throw new TypeError(`${where}: layer "${layer.id}" has a duplicate role id "${role.id}"`);
			roleIds.add(role.id);
			if (role.prompt.trim().length === 0) throw new TypeError(`${where}: role "${role.id}" has an empty prompt`);
		}
		if (layer.kind === "verify" && layer.quorum === void 0) throw new TypeError(`${where}: verify layer "${layer.id}" needs a quorum`);
		if (layer.kind !== "verify" && layer.quorum !== void 0) throw new TypeError(`${where}: only a verify layer may declare a quorum ("${layer.id}")`);
		if (layer.kind === "verify" && layer.quorum?.rule === "threshold") {
			const threshold = layer.quorum.threshold;
			if (threshold === void 0 || threshold < 1 || threshold > width) throw new TypeError(`${where}: verify layer "${layer.id}" needs a threshold between 1 and its width ${width}`);
		}
		if (layer.kind === "reduce" && (layer.roles.length !== 1 || (layer.roles[0]?.count ?? 1) !== 1)) throw new TypeError(`${where}: reduce layer "${layer.id}" must have exactly one role instance`);
	}
}
//#endregion
//#region src/index.ts
/** Cordis plugin name for the host row. */
const name = "tool-council-host";
const SessionRoleTuneSchema = z.object({
	count: z.number().step(1).min(1).max(64),
	model: z.string(),
	provider: z.string(),
	prompt: z.string()
});
const SessionQuorumTuneSchema = z.object({
	rule: z.union([
		"majority",
		"unanimous",
		"threshold"
	]),
	threshold: z.number().step(1).min(1).max(64)
});
const SessionRoleAuthorSchema = z.object({
	id: z.string(),
	label: z.string(),
	prompt: z.string(),
	count: z.number().step(1).min(1).max(64),
	model: z.string(),
	provider: z.string()
});
const SessionLayerAuthorSchema = z.object({
	id: z.string(),
	label: z.string(),
	kind: z.union([
		"map",
		"verify",
		"reduce"
	]),
	roles: z.array(SessionRoleAuthorSchema).default([]),
	quorum: SessionQuorumTuneSchema.default(void 0)
});
const PresetTemplateSchema = z.object({
	id: z.string(),
	label: z.string(),
	layers: z.array(SessionLayerAuthorSchema).default([])
});
const SessionCouncilSetupSchema = z.object({
	presetId: z.string(),
	name: z.string(),
	verifyEnabled: z.boolean(),
	roles: z.dict(SessionRoleTuneSchema).default({}),
	quorum: SessionQuorumTuneSchema.default(void 0),
	addRoles: z.dict(z.array(SessionRoleAuthorSchema)).default({}),
	addLayers: z.array(SessionLayerAuthorSchema).default([]),
	topology: z.array(SessionLayerAuthorSchema).default([])
});
/**
* Schema for the `council` settings section. `topology`, `maxAgentsPerLayer`,
* and `agentPresetId` are written by the composition as the section's `base`
* layer and are never user fields; they exist so the composer-dock designer
* can render the deployment's real presets and layers and refuse an over-wide
* session setup before the write, and so the Council tab can gate on the
* preset id this deployment actually published.
*/
const CouncilSettingsSchema = z.object({
	topology: z.array(z.any()).default([]),
	maxAgentsPerLayer: z.number().step(1).min(1).max(100).default(100),
	maxLayers: z.number().step(1).min(1).max(16).default(6),
	agentPresetId: z.string().default("map-reduce"),
	defaultPreset: z.string().default("bug-hunt"),
	costPerMillionTokens: z.number().min(0).max(1e4).default(0),
	sessionCouncil: z.dict(SessionCouncilSetupSchema).default({}),
	roleLibrary: z.dict(SessionRoleAuthorSchema).default({}),
	presetLibrary: z.dict(PresetTemplateSchema).default({})
});
/** Schemastery configuration for the host row. */
const Config = z.object({
	installPreset: z.boolean().default(true),
	presetId: z.string().default("map-reduce"),
	presetSource: z.string().default("standard"),
	presetName: z.string().default("Map-Reduce mode"),
	presetDescription: z.string().default("Standard mode plus the council: one task fans out to independent members, their findings are deduplicated, verified by a separate panel, and reduced to a quorum report."),
	presetOrder: z.number().step(1).min(0).max(1e3).default(10),
	presetPluginName: z.string().default("@starsinc1708/dsh-tool-council/tool"),
	councilPolicy: z.any()
});
/**
* Render the rows appended to the source composition.
*
* The council tool injects the workflow engine, which is a SERVICE — and on the
* agent plane a service row must sit inside a group carrying an `isolate` realm
* or it publishes process-global and collides with every other preset. So the
* tool ships inside its own entry-local group together with a private
* `workflow-worker-thread` provider, exactly mirroring the delegation group the
* standard preset already carries (whose isolated engine is invisible outside
* that group).
* @param pluginName - module specifier to mount.
* @param toolConfig - YAML mapping lines for the tool row's `config`, or empty.
* @returns the YAML list entries to append.
*/
function composeRows(pluginName, toolConfig) {
	const head = [
		"# The council itself, plus its private workflow engine. Present on this",
		"# plane and no other, which is what distinguishes this mode from the",
		"# preset it was derived from.",
		"- id: council",
		"  name: cordis:group",
		"  group: true",
		"  isolate:",
		"    workflowEngine: true",
		"  config:",
		"    - id: council-workflow-worker",
		"      name: '@deepseek-ai/dsh-workflow-worker-thread'",
		"      config:",
		"        provider: spawn",
		"    - id: tool-council",
		`      name: ${JSON.stringify(pluginName)}`
	];
	const body = toolConfig.trim();
	if (body === "") return head.join("\n");
	const indented = body.split("\n").map((line) => line.trim() === "" ? "" : `        ${line}`);
	return [
		...head,
		"      config:",
		...indented
	].join("\n");
}
/**
* Serialize the raw `councilPolicy` back to YAML for the published preset's
* tool row. Omitted policy → empty (the tool's schema defaults apply).
* @param policy - the raw user-declared policy, or undefined.
* @returns YAML mapping lines, or an empty string.
*/
function toolConfigOf(policy) {
	if (policy === void 0 || policy === null) return "";
	if (typeof policy === "object" && !Array.isArray(policy) && Object.keys(policy).length === 0) return "";
	return dump(policy, {
		noRefs: true,
		lineWidth: -1
	}).trimEnd();
}
/**
* Refuse a user layer that shadows a composition mirror.
*
* The designer reads all three: `topology` decides which presets and layers it
* draws, `maxAgentsPerLayer` its ceiling checks, `agentPresetId` the Council
* tab's gate. Shadowing any of them would move what the surfaces believe
* without moving what the tool runs.
* @param value - the resolved section (composition base under the user layer).
* @param mirrors - the composition's own values, captured at registration.
* @throws TypeError naming the field a user layer tried to set.
*/
function assertMirrorsUnchanged(value, mirrors) {
	if (value.maxAgentsPerLayer !== void 0 && value.maxAgentsPerLayer !== mirrors.maxAgentsPerLayer) throw new TypeError("council: maxAgentsPerLayer mirrors the composition and cannot be set here");
	if (value.maxLayers !== void 0 && value.maxLayers !== mirrors.maxLayers) throw new TypeError("council: maxLayers mirrors the composition and cannot be set here");
	if (value.agentPresetId !== void 0 && value.agentPresetId !== mirrors.agentPresetId) throw new TypeError("council: agentPresetId mirrors the composition and cannot be set here");
	if (value.defaultPreset !== void 0 && value.defaultPreset !== mirrors.defaultPresetId) throw new TypeError("council: defaultPreset mirrors the composition and cannot be set here");
	if (value.topology !== void 0 && JSON.stringify(value.topology) !== mirrors.topologyJson) throw new TypeError("council: topology mirrors the composition and cannot be set here");
}
/**
* Register the host row: own the `council` settings namespace and publish the
* Map-Reduce preset.
* @param ctx - the plugin context; the roster and settings are read optionally.
* @param config - the loader-normalized configuration.
*/
function apply(ctx, config) {
	const policy = resolveConfig(config.councilPolicy ?? {});
	const presetId = config.presetId ?? "map-reduce";
	const baseTopology = toTopology(policy.presets);
	const mirrors = {
		topologyJson: JSON.stringify(baseTopology),
		maxAgentsPerLayer: policy.maxAgentsPerLayer,
		maxLayers: policy.maxLayers,
		agentPresetId: presetId,
		defaultPresetId: policy.defaultPreset.id
	};
	installSettingsSection(ctx, settingsNamespace(COUNCIL_NAMESPACE), CouncilSettingsSchema, {
		topology: baseTopology,
		maxAgentsPerLayer: policy.maxAgentsPerLayer,
		maxLayers: policy.maxLayers,
		agentPresetId: presetId,
		defaultPreset: policy.defaultPreset.id
	}, {
		setSource: () => {},
		onChange: () => {},
		validate: (value) => {
			assertMirrorsUnchanged(value, mirrors);
		}
	});
	if (config.installPreset === false) return;
	const options = {
		presetId,
		sourceId: config.presetSource ?? "standard",
		name: config.presetName ?? "Map-Reduce mode",
		description: config.presetDescription ?? "",
		order: config.presetOrder ?? 10,
		rows: composeRows(config.presetPluginName ?? "@starsinc1708/dsh-tool-council/tool", toolConfigOf(config.councilPolicy))
	};
	ctx.effect(() => {
		let disposed = false;
		const timer = setTimeout(async () => {
			const outcome = await ensurePreset(ctx.get("agentPresets"), options);
			if (disposed) return;
			if (outcome.kind === "installed") ctx.logger.info("dsh-tool-council: published the %s preset at %s", options.presetId, outcome.path);
			else if (outcome.kind === "failed") ctx.logger.warn("dsh-tool-council: could not publish the %s preset — %s", options.presetId, outcome.reason);
			else if (outcome.kind === "skipped") ctx.logger.info("dsh-tool-council: no %s preset published — %s", options.presetId, outcome.reason);
		}, 0);
		return () => {
			disposed = true;
			clearTimeout(timer);
		};
	}, "dsh-tool-council: preset installer lifetime");
}
//#endregion
export { Config, CouncilSettingsSchema, apply, assertMirrorsUnchanged, composeRows, name };
