/**
 * Publishes the council as an agent PRESET — the entry the Web composer's mode
 * menu lists beside Standard, PTC, Minimal and Creator.
 *
 * A preset is a directory under a roster root holding `agent.cordis.yml` (the
 * agent-plane composition) and `preset.yml` (its display metadata). The roster
 * always scans `$DSH_HOME/.agent-presets` — that is `dsh-agent-presets`' own
 * `includeUserRoot` default — so writing a directory there is the whole
 * installation. Discovery is unmemoized, so the mode appears without a restart.
 *
 * Deriving rather than vendoring. The composition is a WHOLE agent plane, not a
 * delta: `standard` is ~250 rows. Shipping a snapshot of it would silently drift
 * from the harness on every upgrade and compose a mode out of last release's
 * rows. So the source text is read back from the installed roster through
 * `read()` and this package appends only its own rows — the mode is always the
 * current harness plus the council.
 *
 * Why the roster is read structurally. `@deepseek-ai/dsh-agent-presets` is
 * supplied by the harness installation, not by this package, and the npm-published
 * copy lags the installed one. Naming the shape here rather than importing it
 * keeps the plugin loadable against either, and the two members used are the ones
 * the service README documents.
 *
 * @module @starsinc1708/dsh-tool-council
 */

import { createHash } from 'node:crypto'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

/** One roster root, as `ctx.agentPresets.roots` reports it. */
export interface PresetRootLike {
  /** Absolute directory the roster scans. */
  readonly path: string
  /** `user` roots are writable; `system` roots ship with the deployment. */
  readonly trust: string
}

/** The slice of `ctx.agentPresets` this installer uses. */
export interface AgentPresetsLike {
  /** Every configured root in order, then the derived harness-home root. */
  readonly roots: readonly PresetRootLike[]
  /** One preset's composition text, exactly as stored. */
  read: (id: string) => Promise<string>
}

/** What the installer was asked to publish. */
export interface PresetInstallOptions {
  /** Directory name and roster id. Must match `[a-z0-9][a-z0-9-]*`. */
  readonly presetId: string
  /** Preset whose composition is the base. */
  readonly sourceId: string
  /** Display name, rendered verbatim — a user-trust preset is never translated. */
  readonly name: string
  /** Display description, rendered verbatim. */
  readonly description: string
  /** Roster sort order. */
  readonly order: number
  /** The rows appended to the source composition, already YAML. */
  readonly rows: string
}

/**
 * What the installer did. Every arm is a normal outcome except `failed`: a
 * deployment with no roster, no writable root, or no source preset is a valid
 * deployment that simply cannot carry a mode, and the tool still registers.
 */
export type PresetInstallOutcome =
  | { readonly kind: 'installed', readonly path: string }
  | { readonly kind: 'unchanged', readonly path: string }
  | { readonly kind: 'skipped', readonly reason: string }
  | { readonly kind: 'failed', readonly reason: string }

/** Preset ids the roster accepts as directory names. */
const PRESET_ID = /^[a-z0-9][a-z0-9-]*$/u

/** Marker line carrying the derivation stamp, so a rewrite is decidable. */
const STAMP_PREFIX = '# dsh-tool-council:stamp '

/**
 * Compose the preset's `agent.cordis.yml` from its source composition.
 *
 * The stamp covers the source text AND the appended rows, so an upgraded
 * harness (new source) and a reconfigured council (new rows) both invalidate an
 * installed copy, while a byte-identical derivation rewrites nothing.
 * @param source - the source preset's composition text, verbatim.
 * @param rows - this package's rows, as YAML list entries.
 * @param sourceId - the source preset's id, recorded in the header.
 * @returns the composition text to write, stamp included.
 */
export function composePreset(source: string, rows: string, sourceId: string): string {
  const stamp = createHash('sha256').update(source).update('\0').update(rows).digest('hex').slice(0, 16)
  const body = `${source.trimEnd()}\n\n${rows.trimEnd()}\n`
  return [
    `# GENERATED by @starsinc1708/dsh-tool-council — derived from the "${sourceId}" preset.`,
    '#',
    '# Edits are lost: the plugin rewrites this file whenever the source preset or',
    '# its own rows change. To diverge, copy this directory under a new id and',
    '# remove that preset from the plugin config (installPreset: false).',
    `${STAMP_PREFIX}${stamp}`,
    '',
    body,
  ].join('\n')
}

/**
 * Read the stamp a previously installed composition carries.
 * @param text - an installed `agent.cordis.yml`.
 * @returns the stamp, or undefined when the file is absent or hand-written.
 */
export function readStamp(text: string): string | undefined {
  for (const line of text.split('\n', 16)) {
    if (line.startsWith(STAMP_PREFIX)) return line.slice(STAMP_PREFIX.length).trim()
  }
  return undefined
}

/**
 * Render `preset.yml`. The roster localizes only `system`-trust built-ins, so a
 * user-trust preset's own metadata is what the mode menu shows, verbatim.
 * @param options - the display metadata.
 * @returns the file text.
 */
export function composeMetadata(options: PresetInstallOptions): string {
  return [
    `name: ${JSON.stringify(options.name)}`,
    `description: ${JSON.stringify(options.description)}`,
    `order: ${options.order}`,
    '',
  ].join('\n')
}

/**
 * Publish the council preset into the roster's writable root, idempotently.
 *
 * Never throws for a deployment that cannot carry a preset — the tool itself
 * stays usable in whatever mode the deployment does compose.
 * @param presets - the roster service, or undefined when none is composed.
 * @param options - what to publish.
 * @returns what happened, for the caller to log.
 */
export async function ensurePreset(
  presets: AgentPresetsLike | undefined,
  options: PresetInstallOptions,
): Promise<PresetInstallOutcome> {
  if (presets === undefined) {
    return { kind: 'skipped', reason: 'no agent-preset roster is composed' }
  }
  if (!PRESET_ID.test(options.presetId)) {
    return { kind: 'failed', reason: `preset id ${JSON.stringify(options.presetId)} is not a usable directory name` }
  }
  const root = presets.roots.find(candidate => candidate.trust === 'user')
  if (root === undefined) {
    return { kind: 'skipped', reason: 'the roster exposes no writable root' }
  }

  let source: string
  try {
    source = await presets.read(options.sourceId)
  } catch (error: unknown) {
    return { kind: 'skipped', reason: `source preset ${JSON.stringify(options.sourceId)} is unreadable — ${messageOf(error)}` }
  }

  const composition = composePreset(source, options.rows, options.sourceId)
  const directory = join(root.path, options.presetId)
  const compositionPath = join(directory, 'agent.cordis.yml')

  const installed = await readIfPresent(compositionPath)
  if (installed !== undefined && readStamp(installed) === readStamp(composition)) {
    return { kind: 'unchanged', path: directory }
  }

  try {
    await mkdir(directory, { recursive: true })
    await writeFile(compositionPath, composition, 'utf8')
    await writeFile(join(directory, 'preset.yml'), composeMetadata(options), 'utf8')
  } catch (error: unknown) {
    return { kind: 'failed', reason: `could not write ${directory} — ${messageOf(error)}` }
  }
  return { kind: 'installed', path: directory }
}

/**
 * Read a file, treating absence as absence rather than as an error.
 * @param path - the file to read.
 * @returns its text, or undefined when it does not exist.
 */
async function readIfPresent(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, 'utf8')
  } catch {
    return undefined
  }
}

/**
 * One line describing a thrown value.
 * @param error - the thrown value.
 * @returns its message, or its string form.
 */
function messageOf(error: unknown): string {
  return error instanceof Error ? error.message : String(error)
}
